# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca27394eaf52b36f26bca061fde61f2a1f041519c7cb707e0a7f507cf411d59f169f06ded42fc6180b01e758ce85255fc5284b2f868578b158b2803ba0efe685

test:
  secret_key_base: fc1786e63559d731349b68e188f013c3c9cce49f84c1e3409a4405b65b4eebd55377f2182274e6f324ff97eba8bb07e10126c4c0a17f965b3fb78b237b729008

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
